#ifndef _DECLARATIONS_H_
#define _DECLARATIONS_H_

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_TITLE "Non-Gravitar"
#define FUEL_START_VALUE 10000
#define LIVES_START_VALUE 5
#define ACCELERATION_MODULE 50.f
#define ANGULAR_SPEED_MODULE 120.f
#define BULLET_BASE_SPEED 180.f
#define SPACESHIP_SHOOT_COOLDOWN 0.33f
#define OUT_OF_BOUNDS_OFFSET_X 400
#define OUT_OF_BOUNDS_OFFSET_Y 300
#define MIN_PLANETS 2
#define MAX_PLANETS 2
#define BUNKER_SHOOT_COOLDOWN 0.33f
#define LIFE_BARS_LENGTH 100.f
#define BUNKER_WIDTH 400
#define BUNKER_HEIGHT 550.f
#define MAX_RAY 0.80f
#define FATTORE_SPOSTAMENTO_ANGOLARE_SPARO 0.10f

#endif