#ifndef _DECLARATIONS_H_
#define _DECLARATIONS_H_

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_TITLE "Non-Gravitar"
#define FUEL_START_VALUE 10000
#define LIVES_START_VALUE 5
#define ACCELERATION_MODULE 50.f
#define ANGULAR_SPEED_MODULE 120.f

#endif