#ifndef _DECLARATIONS_H_
#define _DECLARATIONS_H_

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_TITLE "Non-Gravitar"
#define FUEL_START_VALUE 10000
#define LIVES_START_VALUE 5
#define ACCELERATION_MODULE 50.f
#define ANGULAR_SPEED_MODULE 120.f
#define BULLET_BASE_SPEED 180.f
#define SPACESHIP_SHOOT_COOLDOWN 0.33f
#define OUT_OF_BOUNDS_OFFSET_X 400
#define OUT_OF_BOUNDS_OFFSET_Y 300
#define BUNKER_SHOOT_COOLDOWN 0.99f
#define MAX_LENGTH_LIFE_BARS 100.f
#define BUNKER_WIDTH 400
#define BUNKER_HEIGHT 550.f

#endif